name: Build APK Motion X (Debug)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Tarik Kode
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependensi
        run: |
          cd motionx
          flutter pub get

      - name: Rakit APK Debug (Cepat & Anti Gagal)
        run: |
          cd motionx
          flutter build apk --debug

      - name: Upload APK ke Link Bashupload
        run: |
          cd motionx
          curl https://bashupload.com/ -T build/app/outputs/flutter-apk/app-debug.apk
