name: Build APK Motion X
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v3

      - name: Setup Java (Wajib buat Android SDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependensi & Rakit APK Debug
        run: |
          cd motionx
          flutter pub get
          flutter build apk --debug

      - name: Upload APK ke Artifacts (Biar lu bisa download dari GitHub)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: motionx/build/app/outputs/flutter-apk/app-debug.apk
